# Generated by Django 3.1.5 on 2021-03-19 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, unique=True)),
                ('post_slug', models.SlugField(max_length=200, unique=True)),
                ('post_description', models.TextField()),
                ('post_description_1', models.TextField()),
                ('post_description_2', models.TextField()),
                ('post_description_3', models.TextField()),
                ('post_text_1', models.CharField(blank=True, max_length=200, null=True)),
                ('post_text_2', models.CharField(blank=True, max_length=200, null=True)),
                ('post_text_3', models.CharField(blank=True, max_length=200, null=True)),
                ('post_video', models.CharField(blank=True, max_length=200, null=True)),
                ('post_image', models.ImageField(default='posts/default.jpg', upload_to='posts')),
                ('post_featured', models.BooleanField(default=True)),
                ('post_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('post_updated_at', models.DateTimeField(auto_now=True)),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post_created_at'],
            },
        ),
    ]
