# Generated by Django 3.1.5 on 2021-03-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_category_name', models.CharField(db_index=True, max_length=200)),
                ('post_category_slug', models.SlugField(max_length=200, unique=True)),
                ('post_category_image', models.ImageField(default='posts/category/default.jpg', upload_to='posts/category')),
            ],
        ),
    ]
