# Generated by Django 3.1.5 on 2021-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_owner_name', models.CharField(db_index=True, max_length=200)),
                ('post_owner_image', models.ImageField(default='posts/owner/default.jpg', upload_to='posts/owner')),
            ],
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='post_category_slug',
        ),
    ]
