# Generated by Django 3.1.5 on 2021-03-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210319_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owners_posts', to='posts.postowner'),
            preserve_default=False,
        ),
    ]
