# Generated by Django 3.1.5 on 2021-03-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_slug',
        ),
    ]
