# Generated by Django 3.1.7 on 2021-04-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210323_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
