# Generated by Django 3.1.7 on 2021-04-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_post_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='postowner',
            name='post_owner_meta',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
