# Generated by Django 3.1.7 on 2021-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        ('posts', '0014_postowner_post_owner_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_plan',
            field=models.ManyToManyField(to='memberships.Plan'),
        ),
    ]
