# Generated by Django 3.1.7 on 2021-04-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_post_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
    ]
