# Generated by Django 3.1.7 on 2021-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_post_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_unique_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
