# Generated by Django 3.1.7 on 2021-04-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_auto_20210417_0736'),
        ('posts', '0017_post_post_unique_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_plan',
            field=models.ManyToManyField(related_name='plans', to='memberships.Plan'),
        ),
    ]
