# Generated by Django 3.1.7 on 2021-04-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20210417_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.IntegerField(choices=[(0, 'Vázlat'), (1, 'Publikálva')], default=0),
        ),
    ]
