# Generated by Django 3.1.7 on 2021-04-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210323_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_author',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_mobile_id',
        ),
        migrations.AddField(
            model_name='page',
            name='page_slug',
            field=models.CharField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
