# Generated by Django 3.1.7 on 2021-04-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210417_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_status',
            field=models.IntegerField(choices=[(0, 'Vázlat'), (1, 'Publikálva')], default=0),
        ),
    ]
