# Generated by Django 3.1.7 on 2021-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200, unique=True)),
                ('contact_email', models.CharField(max_length=254)),
                ('contact_message', models.TextField()),
                ('contact_status', models.IntegerField(choices=[(0, 'Új'), (1, 'Folyamatban'), (2, 'Lezárva')], default=0)),
                ('contact_updated_at', models.DateTimeField(auto_now=True)),
                ('contact_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-contact_created_at'],
            },
        ),
    ]
