# Generated by Django 3.1.7 on 2021-04-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_uid', models.CharField(max_length=200, unique=True)),
                ('account_email', models.CharField(db_index=True, max_length=200)),
                ('account_updated_at', models.DateTimeField(auto_now=True)),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
