# Generated by Django 3.1.7 on 2021-04-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200, unique=True)),
                ('plan_slug', models.CharField(max_length=200, unique=True)),
                ('plan_description', models.TextField()),
                ('plan_length', models.IntegerField(default=1)),
                ('plan_price', models.IntegerField(default=0)),
                ('plan_image', models.ImageField(default='plans/default.jpg', upload_to='plans')),
                ('plan_status', models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Active')], default=0)),
                ('plan_updated_at', models.DateTimeField(auto_now=True)),
                ('plan_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-plan_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('member_email', models.CharField(max_length=200)),
                ('member_uid', models.CharField(max_length=254, unique=True)),
                ('member_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('member_since', models.DateField()),
                ('member_expires', models.DateField()),
                ('member_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_plans', to='memberships.plan')),
            ],
        ),
    ]
