# Generated by Django 3.1.7 on 2021-04-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_uid',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
