# Generated by Django 3.1.7 on 2021-04-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20210412_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_slug',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Publish')], default='free', max_length=200, unique=True),
        ),
    ]
