# Generated by Django 3.1.7 on 2021-04-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auto_20210416_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_slug',
            field=models.CharField(choices=[('free', 'free'), ('plan_1', 'plan_1'), ('plan_2', 'plan_2'), ('plan_3', 'plan_3'), ('plan_4', 'plan_4'), ('plan_5', 'plan_5')], default='free', max_length=200, unique=True),
        ),
    ]
