# Generated by Django 3.1.7 on 2021-04-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_auto_20210417_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_status',
            field=models.IntegerField(choices=[(0, 'Inaktív'), (1, 'Aktív')], default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_status',
            field=models.IntegerField(choices=[(0, 'Vázlat'), (1, 'Publikálva')], default=0),
        ),
    ]
