# Generated by Django 3.1.7 on 2021-04-03 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category_name', models.CharField(db_index=True, max_length=200)),
                ('blog_category_image', models.ImageField(default='blog/category/default.jpg', upload_to='blog/category')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, unique=True)),
                ('blog_description', models.TextField()),
                ('blog_image', models.ImageField(default='blog/default.jpg', upload_to='blog')),
                ('blog_featured', models.BooleanField(default=True)),
                ('blog_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('blog_updated_at', models.DateTimeField(auto_now=True)),
                ('blog_created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors_blogs', to=settings.AUTH_USER_MODEL)),
                ('blog_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_blogs', to='blog.blogcategory')),
            ],
            options={
                'ordering': ['-blog_created_at'],
            },
        ),
    ]
