# Generated by Django 3.1.7 on 2021-04-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_owner_name', models.CharField(db_index=True, max_length=200)),
                ('blog_owner_meta', models.CharField(max_length=254)),
                ('blog_owner_image', models.ImageField(default='blog/owner/default.jpg', upload_to='blog/owner')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners_blogs', to='blog.blogowner'),
        ),
    ]
